import type { Metadata } from "next";
import "./globals.css";

import { Inter, Poppins, DM_Sans } from "next/font/google";
import "./globals.css";

const bodyFont = Inter({
  subsets: ["latin"],
  variable: "--font-body",
});

const subFont = DM_Sans({
  subsets: ["latin"],
  variable: "--font-sub",
});

const heroFont = Poppins({
  subsets: ["latin"],
  weight: ["600", "700"],
  variable: "--font-hero",
});




export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
   <body className={`${bodyFont.variable} ${subFont.variable} ${heroFont.variable}`}>
  {children}
</body>

    </html>
  );
}
